name: Generate inventory file

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - name: Run the command
      run: node ./generate-inventory-file.js | tee ./inventory.json
    - name: Commit changes to inventory.json
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
